language: emacs-lisp
sudo: true
env:
  matrix:
    - EMACS=emacs24        EMACS_PPA=ppa:cassou/emacs
    - EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
  global:
    secure: YcMrnDekniVjfY1kQeGmuGIHQRFQM5Kf64HURs2QhGNqoIePfDIHOCfWh4HI3fhdYQLHy/+sLpr6RUEF4iVoDi5XrjsPq7faVhE+NmHWFoWG8eLMjxm1krK1WC2c17lczQKArIkQnA/zILxg4okD4WvCYOBRcOGlIKpQEV7yKBg=
notifications:
  email: false
branches:
  only:
    - master
    - v2
before_install:
  - sudo add-apt-repository -y "$EMACS_PPA"
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes -qq "$EMACS"
  - sudo apt-get install --force-yes -qq "${EMACS}-el" || true # OK to fail
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - '"$EMACS" --version'
script:
  - make clean
  - make bootstrap
