language: generic
env:
  matrix:
    - EMACS=emacs-snapshot
  global:
    secure: YcMrnDekniVjfY1kQeGmuGIHQRFQM5Kf64HURs2QhGNqoIePfDIHOCfWh4HI3fhdYQLHy/+sLpr6RUEF4iVoDi5XrjsPq7faVhE+NmHWFoWG8eLMjxm1krK1WC2c17lczQKArIkQnA/zILxg4okD4WvCYOBRcOGlIKpQEV7yKBg=
notifications:
  email: false
branches:
  only:
    - master
    - develop
before_install:
  - if [ "$EMACS" == 'emacs-snapshot' ]; then sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
        && sudo apt-get -qq update && sudo apt-get -qq -f install && sudo apt-get -qqy install emacs-snapshot; fi
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - cask install
  - '"$EMACS" --version'
script:
  - make clean
  - make bootstrap
